language: python
python:
  - "2.7"
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -r dev_requirements.txt"
  - "npm install"
script: 
  - "py.test test/"
