# Site settings
title: Easy Call
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/easy-call/"
url: "http://thesedateone.github.io"
github_username:  thesedateone

# Build settings
markdown: kramdown
