# Site settings
title: Easy Call
description: > # this means to ignore newlines until "baseurl:"
  Easy Call is a simple web based app for streamlining your outbound call centre.
  This is the place where you can get updates, read documentation and find contact information
  if you use or administer an install of Easy Call.  The Github repository is the place to
  contribute to the project directly.
baseurl: "/easy-call"
url: "http://thesedateone.github.io"
github_username:  thesedateone/easy-call
twitter_username: "@jacquesbeukes"

# Build settings
markdown: kramdown
